# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-05-06 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twittr', '0002_auto_20170504_1241'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=140)),
                ('created', models.DateTimeField()),
                ('retweet_count', models.PositiveIntegerField()),
                ('is_quote', models.BooleanField()),
                ('is_image', models.BooleanField()),
                ('is_video', models.BooleanField()),
                ('has_mentions', models.BooleanField()),
                ('media_url', models.CharField(max_length=500)),
            ],
        ),
    ]
