# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-05-06 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twittr', '0003_tweet'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitterprofile',
            name='tweets',
            field=models.ManyToManyField(to='twittr.Tweet'),
        ),
    ]
