# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-05-07 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twittr', '0004_twitterprofile_tweets'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='is_reply',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='has_mentions',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='is_image',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='is_quote',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='is_video',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='retweet_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
