# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-05-07 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twittr', '0005_auto_20170507_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='retweet_count',
        ),
        migrations.AddField(
            model_name='tweet',
            name='is_retweet',
            field=models.BooleanField(default=False),
        ),
    ]
