# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-05-08 16:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twittr', '0006_auto_20170507_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='has_mentions',
        ),
    ]
