# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-09-04 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twittr', '0007_remove_tweet_has_mentions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='id',
        ),
        migrations.AddField(
            model_name='tweet',
            name='temp',
            field=models.CharField(default=0, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='text',
            field=models.CharField(max_length=200),
        ),
    ]
