# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-09-04 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twittr', '0008_auto_20170904_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='text',
            field=models.CharField(max_length=500),
        ),
    ]
